### ISSUE TITLE
macOS查看离线下载列表崩溃

### ISSUE THREAD

**Issue by 45gfg9** [iikira/BaiduPCS-Go#344]
```
BaiduPCS-Go:/ 45gfg9$ od l
panic: interface conversion: interface {} is *baidupcs.cloudDlQueryTaskJSON, not *baidupcs.cloudDlListTaskJSON

goroutine 1 [running]:
github.com/iikira/BaiduPCS-Go/baidupcs.handleJSONParse(0x15c7e72, 0x1e, 0x1c5d020, 0xc4204501c0, 0x1564600, 0xc4203b7570, 0x0, 0xc420023b50)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/baidupcs/jsontable.go:136 +0xafd
github.com/iikira/BaiduPCS-Go/baidupcs.(*BaiduPCS).cloudDlQueryTask(0xc420314780, 0x15c7e72, 0x1e, 0xc420023b90, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/baidupcs/cloud_dl.go:161 +0x2c8
github.com/iikira/BaiduPCS-Go/baidupcs.(*BaiduPCS).CloudDlListTask(0xc420314780, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/baidupcs/cloud_dl.go:232 +0x36f
github.com/iikira/BaiduPCS-Go/internal/pcscommand.RunCloudDlListTask()
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcscommand/cloud_dl.go:41 +0x2e
main.main.func37(0xc42010d080, 0x0, 0xc42010d080)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:1486 +0x20
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.HandleAction(0x14f0fe0, 0x15dee68, 0xc42010d080, 0xc420075000, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.Command.Run(0x15b5487, 0x4, 0x0, 0x0, 0xc4203147e0, 0x2, 0x2, 0x15c7e72, 0x1e, 0xc420021720, ...)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc42001fd40, 0xc42010cdc0, 0x0, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:379 +0xa10
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.Command.startApp(0x15ba260, 0x9, 0x0, 0x0, 0xc4203147c0, 0x2, 0x2, 0x15bc4ba, 0xc, 0x0, ...)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/command.go:298 +0x8d9
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.Command.Run(0x15ba260, 0x9, 0x0, 0x0, 0xc4203147c0, 0x2, 0x2, 0x15bc4ba, 0xc, 0x0, ...)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/command.go:98 +0x1246
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).Run(0xc42001fba0, 0xc420317380, 0x3, 0x3, 0x0, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main.func1(0xc42010cb00)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:322 +0x657
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.HandleAction(0x14e0280, 0xc4202e7930, 0xc42010cb00, 0xc420074de0, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:492 +0x7c
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).Run(0xc42001fba0, 0xc42001c1d0, 0x1, 0x1, 0x0, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:264 +0x5ee
main.main()
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:1776 +0x5186
```

**Comment by iikira** [comment]
应该修复了, 8340bb7
