### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by VinylChloride** [iikira/BaiduPCS-Go#355]
控制台输出：

> BaiduPCS-Go:XXX库 大XXXX$ upload C:/Users/Vinyl/Desktop/pendUpload/* .
[1] 加入上传队列: C:/Users/Vinyl/Desktop/pendUpload/[Music]Hacknet_OST.7z
[2] 加入上传队列: C:/Users/Vinyl/Desktop/pendUpload/[Music]Narcissu_10th_Anniversary_Anthology_Project_OST.7z
[1] 准备上传: C:/Users/Vinyl/Desktop/pendUpload/[Music]Hacknet_OST.7z
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x83b67c]
goroutine 66 [running]:
github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1.1(0xc042091e50, 0xc0421007d0, 0x4f, 0xc042065cc0, 0xc042089290, 0xc0423d5a70, 0xc0420554a0, 0xc042089288)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:57 +0xec
created by github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:52 +0x1e2

**Comment by VinylChloride** [comment]
经过几次重试又可以了

**Comment by VinylChloride** [comment]
#336
