### ISSUE TITLE
希望作者可以出一个一键删除百度云重复文件的功能

### ISSUE THREAD

**Issue by fatinghenji** [iikira/BaiduPCS-Go#366]
可以通过比对文件的md5找出重复文件，然后进行删除操作。网上有类似教程，但是那个时基于百度自己的重复删除。希望作者可以在下一个版本中增添这一功能

**Comment by iBug** [comment]
我写了个 Python 脚本来处理这个任务，用法：

首先运行 `BaiduPCS-Go export / > export.txt` 导出网盘全部文件的信息，然后运行这个脚本 (Python 3.3+) 可以得到全部重复文件的信息，以及一个 `delete.sh`。直接运行 `sh delete.sh` 就可以调用 BaiduPCS-Go 删除重复文件。

Unix 系统注意将 `BaiduPCS-Go` 二进制所在路径加入 `$PATH`, Windows 系统可以直接改名为 `delete.bat` ，放在同一目录下运行。

```python
#!/usr/bin/env python3

import re

pattern_s = r'BaiduPCS-Go rapidupload -length=(\d+) -md5=([0-9a-f]+) "(.*)"'
pattern = re.compile(pattern_s)

seen = {}
with open("export.txt", "r") as f:
    for line in f:
        match = pattern.match(line.strip())
        if match is None:
            continue
        # print("{}\t{}\t{}".join(match.group(1), match.group(2), match.group(3)))
        key = int(match.group(1)), match.group(2)
        if key not in seen:
            seen[key] = [match.group(3)]
        else:
            seen[key].append(match.group(3))

seen = {k: seen[k] for k in seen if len(seen[k]) >= 2}

print("Total duplicated items: {}".format(len(seen)))
print("Total duplicates: {}".format(sum(len(seen[k]) for k in seen)))
print("Inflated size: {}".format(sum(k[0] * (len(seen[k]) - 1) for k in seen)))
for key in seen:
    print("Duplicate: " + "\n           ".join(seen[key]))

with open("delete.sh", "w") as f:
    for key in seen:
        for item in seen[key][1:]:
            print('BaiduPCS-Go rm "{}"'.format(item), file=f)
```

脚本已测试 (Ubuntu 18.04, Python 3.6.5)

**Comment by iBug** [comment]
@MingqiHuang 谢谢提醒，我长期在 Linux 下码代码都把这茬给忘了

**Comment by fatinghenji** [comment]
emmmm我执行了第一个命令，并没有在本地找到export.txt这个文件，这是正常的吗？

**Comment by fatinghenji** [comment]
补充，作为一个不太懂这些的人，到底怎么使用下面的代码…………

**Comment by MingqiHuang** [comment]
1. 终端（命令提示符）下运行 `BaiduPCS-Go export / > export.txt`，在当前目录会有 `export.txt` 文件
2. 用文本编辑器复制下面的代码，保存到 `export.txt` 所在的目录
3. Python 3 运行上面的 Python 脚本
4. 脚本运行完生成一个 `delete.sh` 在 Windows 下请重命名为 `delete.bat`
5. Unix-like 系统请加上可执行权限，执行生成的 `delete` 脚本

**Comment by fatinghenji** [comment]
我吧上面的代码复制进入notepad++，并保存为后缀为py的文件，但是我双击它的时候仅仅是有一个提示框闪烁了一下
![tim 20180923011153](https://user-images.githubusercontent.com/37131177/45919810-10d90a80-bece-11e8-9b08-d3544a59c3d7.png)

**Comment by fatinghenji** [comment]
我添加了提到的encoding='UTF-8'，但是看起来有些不对

这下面是代码

> #!/usr/bin/env python3

import re

pattern_s = r'BaiduPCS-Go rapidupload -length=(\d+) -md5=([0-9a-f]+) "(.*)"'
pattern = re.compile(pattern_s)

seen = {}
with open("export.txt","r",encoding='UTF-8') as f:
    for line in f:
        match = pattern.match(line.strip())
        if match is None:
            continue
        # print("{}\t{}\t{}".join(match.group(1), match.group(2), match.group(3)))
        key = int(match.group(1)), match.group(2)
        if key not in seen:
            seen[key] = [match.group(3)]
        else:
            seen[key].append(match.group(3))

seen = {k: seen[k] for k in seen if len(seen[k]) >= 2}

print("Total duplicated items: {}".format(len(seen)))
print("Total duplicates: {}".format(sum(len(seen[k]) for k in seen)))
print("Inflated size: {}".format(sum(k[0] * (len(seen[k]) - 1) for k in seen)))
for key in seen:
    print("Duplicate: " + "\n           ".join(seen[key]))

with open("delete.sh","w",encoding='UTF-8') as f:
    for key in seen:
        for item in seen[key][1:]:
            print('BaiduPCS-Go rm "{}"'.format(item), file=f)

**Comment by MingqiHuang** [comment]
> 
> 
> 我添加了提到的encoding='UTF-8'，但是看起来有些不对
> 
> 这下面是代码
> 
> > #!/usr/bin/env python3
> 
> import re
> 
> pattern_s = r'BaiduPCS-Go rapidupload -length=(\d+) -md5=([0-9a-f]+) "(.*)"'
> pattern = re.compile(pattern_s)
> 
> seen = {}
> with open("export.txt","r",encoding='UTF-8') as f:
> for line in f:
> match = pattern.match(line.strip())
> if match is None:
> continue
> # print("{}\t{}\t{}".join(match.group(1), match.group(2), match.group(3)))
> key = int(match.group(1)), match.group(2)
> if key not in seen:
> seen[key] = [match.group(3)]
> else:
> seen[key].append(match.group(3))
> 
> seen = {k: seen[k] for k in seen if len(seen[k]) >= 2}
> 
> print("Total duplicated items: {}".format(len(seen)))
> print("Total duplicates: {}".format(sum(len(seen[k]) for k in seen)))
> print("Inflated size: {}".format(sum(k[0] * (len(seen[k]) - 1) for k in seen)))
> for key in seen:
> print("Duplicate: " + "\n ".join(seen[key]))
> 
> with open("delete.sh","w",encoding='UTF-8') as f:
> for key in seen:
> for item in seen[key][1:]:
> print('BaiduPCS-Go rm "{}"'.format(item), file=f)
> 
> ![tim 20180923015011](https://user-images.githubusercontent.com/37131177/45920196-80052d80-bed3-11e8-9bbf-dad6893b8366.png)

唔，看起来是编码出锅了。修正一下 `delete.bat` 的编码试一下？

**Comment by fatinghenji** [comment]
怎么修正呢？XD

**Comment by iBug** [comment]
> 怎么修正呢？XD

试试在 `open("delete.sh", "w")` 那里加上 `encoding="gbk"`

**Comment by MingqiHuang** [comment]
有大量文件需要删除的时候请求太频繁会报 `pcs refused to service` 错误QAQ

**Comment by fatinghenji** [comment]
> > 大量有需要文件删除的时候请求太频繁会作者：`pcs refused to service`错误QAQ
> 
> 是的我也注意到了，[最新版在`GROUPING`开头加入了一个变量](https://github.com/iBug/pyGadgets/blob/master/BaiduPCS-Go_duplicate_finder/worker.py#L6)，单次请求删除文件的数目。你可以把它改大点（默认10）

我尝试着更新了代码，但是在python shell中运行结束后得到了以下错误代码：
Traceback (most recent call last):
  File "D:\BaiduPCS-Go-v3.5.3-windows-x64\do it.py", line 39, in <module>
    deleting = sum(seen[key][1:] for key in seen)
TypeError: unsupported operand type(s) for +: 'int' and 'list'

**Comment by iBug** [comment]
> 我尝试着更新了代码，但是在python shell中运行结束后得到了以下错误代码：
> Traceback (most recent call last):
> File "D:\BaiduPCS-Go-v3.5.3-windows-x64\do it.py", line 39, in 
> deleting = sum(seen[key][1:] for key in seen)
> TypeError: unsupported operand type(s) for +: 'int' and 'list'

忘了点东西，[现在修好了](https://github.com/iBug/pyGadgets/commit/ad1d735d9abff807a5622340cb3eac5122f2bdd1)

**Comment by fatinghenji** [comment]
貌似依旧有bug存在，好像是一个括弧的问题。
![tim 20180924023237](https://user-images.githubusercontent.com/37131177/45931557-3afbfc80-bfa2-11e8-98d9-2d03f680bcd1.png)

**Comment by iBug** [comment]
> 貌似依旧有bug存在，好像是一个括弧的问题。
> ![tim 20180924023237](https://user-images.githubusercontent.com/37131177/45931557-3afbfc80-bfa2-11e8-98d9-2d03f680bcd1.png)

最近比较晕，抱歉哈，这下应该真的修好了

**Comment by fatinghenji** [comment]
> > 貌似依旧有漏洞存在，好像是一个括弧的问题。
> > ![蒂姆20180924023237](https://user-images.githubusercontent.com/37131177/45931557-3afbfc80-bfa2-11e8-98d9-2d03f680bcd1.png)
> 
> 最近比较晕，抱歉哈，这下应该真的修好了

看起来依旧是有错误的，emmmmmm。
![tim 20180924105847](https://user-images.githubusercontent.com/37131177/45936429-e891fe80-bfe8-11e8-91e4-0e8b0a8cf46f.png)

**Comment by iBug** [comment]
> 看起来依旧是有错误的，emmmmmm。

行了你再试试吧，我又改了，emmmmm

**Comment by fatinghenji** [comment]
> > 看起来依旧是有错误的，emmmmmm。
> 
> 行了你再试试吧，我又改了，emmmmm

emmmmm,依旧报错。
![tim 20180924173152](https://user-images.githubusercontent.com/37131177/45945333-bea7fe80-c01f-11e8-93af-e96fb71a2036.png)

**Comment by iBug** [comment]
好了这回我测试过了，应该真的没问题了

**Comment by fatinghenji** [comment]
> 好了这回我测试过了，应该真的没问题了

![tim 20180924181451](https://user-images.githubusercontent.com/37131177/45948766-e1d8ab00-c02b-11e8-95c1-7a9a20b5888e.png)

**Comment by iBug** [comment]
这看起来很奇怪，如果上面重复文件的信息都能正确输出，下面不应该乱码啊

**Comment by fatinghenji** [comment]
> 这看起来很奇怪，如果上面重复文件的信息都能正确输出，下面不应该乱码啊，并且我本地测试的时候没这个问题

我重新进行一次export再试试

**Comment by fatinghenji** [comment]
> 这看起来很奇怪，如果上面重复文件的信息都能正确输出，下面不应该乱码啊，并且我本地测试的时候没这个问题

补充，执行完py文件后得到的是*.sh而不是*.bat。是否和这个有关呢？

**Comment by iBug** [comment]
肯定有关，我最新的代码应该能检测 Windows 系统并且自动调整这些设定（文件名和编码），我再确认一下

**Comment by fatinghenji** [comment]
> 肯定有关，我最新的代码应该能检测 Windows 系统并且自动调整这些设定（文件名和编码），我再确认一下

补充，输出为*.sh的文件用notepad++打开内容是正常的

**Comment by iBug** [comment]
> 补充，输出为*.sh的文件用notepad++打开内容是正常的

是的，Notepad++能正确识别UTF-8编码。我刚才已经改正错误了，能输出`.bat`和GBK编码的文件了

**Comment by fatinghenji** [comment]
> > 补充，输出为*.sh的文件用notepad++打开内容是正常的
> 
> 是的，Notepad++能正确识别UTF-8编码。我刚才[已经改正错误了](https://github.com/iBug/pyGadgets/commit/21adbc1390878efe4ce260a9c84b285b79c95151)，能输出`.bat`和GBK编码的文件了
成功了！
大佬要不要再考虑做一个云同步的功能啊，执行文件后比对本地和云端制定文件夹中文件的md5，然后实现云端本地文件的同步啊

**Comment by iBug** [comment]
@fatinghenji Python 挺好学的，你可以学习一个，提高自己的姿势水平，然后自己写一个
