### ISSUE TITLE
大文件上传出错

### ISSUE THREAD

**Issue by SeAL80s** [iikira/BaiduPCS-Go#369]
系统：Manjaro x86_64
内存：8G
CPU：i5
大文件上传偶尔会出错，信息如下。能够续传，但是开始位置不同了。从信息上能看到已经上传了6.31G，但是出错续传却是5.32G（大概是这个样子）开始。

[1] ↑ 6.31GB/7.32GB 640.00KB/s in 7m33.08s ............panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x82fa25]

goroutine 61 [running]:
github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1.1(0xc4203ac190, 0xc42042a320, 0x50, 0xc420438460, 0xc4203ae0c8, 0xc4203b04c0, 0xc42041c900, 0xc4203ae0c0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:57 +0xe5
created by github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:52 +0x1db

问题好像是随机出现的

PS:
进一步测试的结果
[1] 准备上传: /run/media/daniel/1TB/Game.of.Thrones.S07.1080p.BluRay.x265.TrueHD.Atmos.7.1-Th3ViSTa/Game.of.Thrones.S07E06.Beyond.the.Wall.1080p.BluRay.x265.TrueHD.Atmos.7.1-Th3ViSTa.mkv
DEBUG: UPLOADER INFO: upload task CREATED from instance state
DEBUG: BAIDUPCS INFO: 分片上传—文件分片及上传 URL: https://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&method=upload&type=tmpfile
DEBUG: BAIDUPCS INFO: 分片上传—文件分片及上传 URL: https://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&method=upload&type=tmpfile
DEBUG: BAIDUPCS INFO: 分片上传—文件分片及上传 URL: https://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&method=upload&type=tmpfile
DEBUG: BAIDUPCS INFO: 分片上传—文件分片及上传 URL: https://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&method=upload&type=tmpfile
DEBUG: BAIDUPCS INFO: 分片上传—文件分片及上传 URL: https://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&method=upload&type=tmpfile
**[1] ↑ 7.15GB/7.32GB 0B/s in 4m51.067s ............panic: runtime error: invalid memory address or nil pointer dereference**
**[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x82fa25]**

goroutine 12 [running]:
github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1.1(0xc420414460, 0xc42040e0a0, 0x50, 0xc420442000, 0xc420334010, 0xc42001c480, 0xc42002a2a0, 0xc420334008)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:57 +0xe5
created by github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:52 +0x1db

7.32G的文件，上传到7.15G报错，然后重传就回到6.7G，基本每次都这样。upload能指定分片数量吗？tmpfile有大小的限制吗？
另外 upload --verbose 会显示命令语法错误，一定要改成--verbose upload 才开启调试模式，有点别扭。
upload --nosplit 问题依旧。还有，文件在Linux ext4上显示7.9G。到了百度，就显示7.3G，这能说明百度网盘是Windows Server吗？还是不同文件系统显示文件大小都不同，不就是个1000和1024的区别吗？

**Comment by SeAL80s** [comment]
可能是文件系统出错，或者文件本身损坏。
