### ISSUE TITLE
在树莓派上编译后可以打开使用，但下载时报错

### ISSUE THREAD

**Issue by niinaranpo** [iikira/BaiduPCS-Go#61]
```
添加下载任务: /temp/Kurage.Hime.Ep05.Chi_Jap.HDTVrip.1280X720.mp4

[ 1 / 1 ] 类型: 文件
文件名: Kurage.Hime.Ep05.Chi_Jap.HDTVrip.1280X720.mp4
文件路径: /temp/Kurage.Hime.Ep05.Chi_Jap.HDTVrip.1280X720.mp4
文件大小: 732908019, (698.955554MB)
md5: f2e2b072e622b8aa6669f0efe783d9d0
fs_id: 999996263412620
创建日期: 2018-02-13 03:55:03
修改日期: 2018-02-13 09:23:20

即将开始下载文件

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x127bc]

goroutine 117 [running]:
sync/atomic.addUint64(0x1133ccf4, 0x2e8, 0x0, 0x400, 0x29104a91)
	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/iikira/BaiduPCS-Go/downloader.(*Downloader).downloadBlock(0x1133ccb0, 0x2f, 0x0, 0x0, 0x0)
	/home/pi/go/src/github.com/iikira/BaiduPCS-Go/downloader/downloader_block.go:236 +0x9bc
github.com/iikira/BaiduPCS-Go/downloader.(*Downloader).downloadBlockFn(0x1133ccb0, 0x2f)
	/home/pi/go/src/github.com/iikira/BaiduPCS-Go/downloader/downloader_block.go:107 +0x7c
github.com/iikira/BaiduPCS-Go/downloader.(*Downloader).download.func1(0x1133ccb0, 0x2f)
	/home/pi/go/src/github.com/iikira/BaiduPCS-Go/downloader/downloader.go:182 +0x24
created by github.com/iikira/BaiduPCS-Go/downloader.(*Downloader).download
	/home/pi/go/src/github.com/iikira/BaiduPCS-Go/downloader/downloader.go:181 +0x44
```

硬件：raspberry pi 3
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
```

**Comment by iikira** [comment]
应该修复了, 08312c8f63f56e59e1b29f5a956d93e9b34360c1, 这是标准库的一个bug

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

https://golang.org/pkg/sync/atomic/#pkg-note-BUG

也就是说, 只有32位操作系统才出现这个问题...

**Comment by niinaranpo** [comment]
已解决
