### ISSUE TITLE
Error:"panic: runtime error: index out of range",同时开启多个"baidupcs-go"进程上传文件时,有一定几率出现bug

### ISSUE THREAD

**Issue by masx200** [iikira/BaiduPCS-Go#869]
同时开启多个"baidupcs-go"进程上传文件时,有一定几率出现bug,虽然上传成功,但是程序报错

`cmd`:

```
 BaiduPCS-Go.exe upload D:\baidupandownload\882ab48745b65338f17c993f80d3f15c.webp /我的图片/微博配图

```

输出 `stderr`:

```


panic: runtime error: index out of range

goroutine 22 [running]:
github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).UpdateUploading(0xc0422e48d0, 0xc042222240, 0xc0420f6ee0)
        /Users/syy/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:101 +0x279
github.com/iikira/BaiduPCS-Go/internal/pcscommand.RunUpload.func2.1(0xa60d20, 0xc042580a80, 0xc04205c240)
        /Users/syy/go/src/github.com/iikira/BaiduPCS-Go/internal/pcscommand/upload.go:355 +0x385
github.com/iikira/BaiduPCS-Go/requester/uploader.(*MultiUploader).uploadStatusEvent.func1(0xc04206aa90)
        /Users/syy/go/src/github.com/iikira/BaiduPCS-Go/requester/uploader/status.go:93 +0x1a1
created by github.com/iikira/BaiduPCS-Go/requester/uploader.(*MultiUploader).uploadStatusEvent
        /Users/syy/go/src/github.com/iikira/BaiduPCS-Go/requester/uploader/status.go:84 +0x4f



   

```

输出 `stdout`:

```

[1] 加入上传队列: D:/baidupandownload/882ab48745b65338f17c993f80d3f15c.webp
[1] 准备上传: D:/baidupandownload/882ab48745b65338f17c993f80d3f15c.webp
[1] 秒传失败, 开始上传文件...


[1] 上传文件成功, 保存到网盘路径: /我的图片/微 博配图/882ab48745b65338f17c993f80d3f15c.webp

```

`Error`信息
```
{
killed: false
code: 2
signal: null

}
```

**Comment by masx200** [comment]
偶尔又遇到另一个问题 上传文件失败的bug

`cmd`:

```

BaiduPCS-Go upload /storage/emulated/0/Pictures/压缩输出图片/5b7b0044a0d25a4913ea1be3f2cbb44e.webp  /我的图片/压缩输出图片

```

标准输出`stdout`如下 

```

"[1] 加入上传队列: /storage/emulated/0/Pictures/压缩输出图片/5b7b0044a0d25a4913ea1be3f2cbb44e.webp\n

打开上传未完成数据库错误: pcsupload.UploadingDatabase.UploadingList: []*pcsupload.Uploading: pcsupload.Uploading.isObjectEnd: object ended prematurely, unexpected char \u0000, error found in #10 byte of ...|581848489}\n|..., bigger context ...|:1581844613,\"state\":null}],\"timestamp\":1581848489}\n|...\n

```
